### ISSUE TITLE
mypy 1.5.1 compatibility

### ISSUE THREAD

**Issue by glyph** [Shoobx/mypy-zope#104]

**Comment by graingert** [comment]
Looks like this was fixed in https://github.com/Shoobx/mypy-zope/pull/103

**Comment by glyph** [comment]
> Looks like this was fixed in #103

That does seem right; I can at least `pip install 'git+https://github.com/Shoobx/mypy-zope'` now and see mypy 1.5.1 come down, although convincing tox to do a full typecheck with that sort of requirement line is a little more work.

I really wish Github would let us track released fixes :-|

**Comment by kedder** [comment]
Yeah, the master of mypy-zope supports 1.5.1, but apparently I haven't made a release. Let me do that now.

**Comment by kedder** [comment]
Done!

**Comment by glyph** [comment]
wow, thanks for the lightning turnaround!
