### ISSUE TITLE
mypy 1.7 support

### ISSUE THREAD

**Issue by glyph** [Shoobx/mypy-zope#107]
currently holding back some upgrades, so filing this for tracking

**Comment by glyph** [comment]
updating since time has moved on :)

**Comment by glyph** [comment]
aw I got all excited seeing #108 but it's just dependabot noticing the same problem

**Comment by kedder** [comment]
You're right, it's a good time for some upgrades :)

**Comment by kedder** [comment]
mypy-zope-1.0.2 released!

**Comment by glyph** [comment]
> mypy-zope-1.0.2 released!

amazing! I was just starting to add some very irritating workarounds for some Mypy bugs fixed in 1.6, so this is excellent timing. Thank you so much for the continued maintenance!

**Comment by wsanchez** [comment]
Thanks @kedder, super glad for the update
