### ISSUE TITLE
Latest release does not contain a wheel

### ISSUE THREAD

**Issue by miketheman** [Shoobx/mypy-zope#118]
This is a repeat of #42 
https://pypi.org/project/mypy-zope/1.0.5/#files shows only an sdist

Prior releases have a wheel:
https://pypi.org/project/mypy-zope/1.0.4/#files
https://pypi.org/project/mypy-zope/1.0.3/#files

Might be worth looking into having GitHub Actions publish the releases? https://docs.pypi.org/trusted-publishers/

**Comment by kedder** [comment]
[1.0.7](https://pypi.org/project/mypy-zope/#files) is released with the wheel. Sorry for late response.

**Comment by miketheman** [comment]
Thanks! Would it make sense to add `zest.releaser[recommended]` to a dev dependencies or such to prevent that from the next time?
