### ISSUE TITLE
upgrade to mypy 740?

### ISSUE THREAD

**Issue by glyph** [Shoobx/mypy-zope#12]
Looks like this is still pinned to 073; just wanted to file this, partially to ask if anyone knows it works? :)

**Comment by kedder** [comment]
Is 0.740 released? No announcement on http://mypy-lang.org/

**Comment by arnimarj** [comment]
It is: https://pypi.org/project/mypy/

No idea why the blog page doesn't reflect the fact...

**Comment by arnimarj** [comment]
FYI I am using the plugin with 0.740. Our use case is limited, but there are no current issues we are aware of.

**Comment by kedder** [comment]
Great, I'll doublecheck and bump the version this evening.

**Comment by kedder** [comment]
mypy-zope-0.2.2 with support for 0.740 released

**Comment by glyph** [comment]
Thanks so much for keeping pace with upstream, @kedder !
