### ISSUE TITLE
Please make a release with "Support future mypy"

### ISSUE THREAD

**Issue by mthuurne** [Shoobx/mypy-zope#2]
I'd like to include mypy-zope in my project, but if I roll back mypy from 0.670 to 0.660 I would get a bunch of false positives. I know I can install the current development state directly from GitHub with pip, but I'm using Poetry to maintain virtualenvs for multiple Python versions and installing packages directly with pip means I'd have to manually do that for every virtualenv, plus I have to manually update them later as well.

So it would really help me if there was a mypy-zope release on PyPI that depends on mypy >= 0.660.

**Comment by kedder** [comment]
Sure. mypy-zope-0.1.2 is released on pypi.

**Comment by mthuurne** [comment]
That was quick. Thanks!
