### ISSUE TITLE
Clearer error message when "self" is used in method inside interface definition

### ISSUE THREAD

**Issue by mthuurne** [Shoobx/mypy-zope#3]
When checking the following modified example:
```py
class IAnimal(zope.interface.Interface):
    def say(self) -> None:
        pass
```
The following error message is output:
```
error: Name 'self' already defined (possibly by an import)
```
While the plugin is correct in flagging this use of `self` as an error, the message is a bit cryptic. It would be nice to have a specific error message for this problem: I imagine I'm not the only one making this mistake in their code.

**Comment by kedder** [comment]
I agree. Plugin can do better here.
