### ISSUE TITLE
TypeError: interpreted classes cannot inherit from compiled

### ISSUE THREAD

**Issue by glyph** [Shoobx/mypy-zope#7]
CI is failing, and I believe this means that this plugin doesn't support the current version of mypy.  So one bug here is just that `setup.py` is insufficiently restrictive as the code stands today; it needs an upper bound on mypy versions.  But as I recall this is an upstream incompatibility introduced in mypy - which version does it break in, and does this require changes in mypy to start working again or is it something this plugin should change?

**Comment by kedder** [comment]
> So one bug here is just that setup.py is insufficiently restrictive as the code stands today

Yes, you're right. I was hoping https://github.com/python/mypy/issues/6706 will be fixed quickly. However with it being fixed now (thanks for following up in that bug), do you still feel we need to release a version of mypy-zope with limiting the mypy version?

**Comment by glyph** [comment]
@kedder Just noticed this was fixed.  Awesome!  A release with a pinned minimum for mypy would be a nice bonus, but I'd say that if things are working again, I'd be happy to see this bug itself closed as fixed, and another more specific one for the version pinning.

(The only reason I'm not closing myself is that I don't have a project set up with this plugin, so I can't confirm that it works quickly.)

**Comment by glyph** [comment]
bump?

**Comment by kedder** [comment]
Sorry, I was away for the last two weeks, will try to catch up with this in the next couple of days.

**Comment by kedder** [comment]
Sigh, this is tricky. It seems like with the latest mypy-v0.720 it is not possible to support the full feature set of mypy-zope, namely the adaptation pattern (`animal = IAnimal(ctx)`), due to refactorings in the mypy. We will have to find some work-arounds to work under latest mypy.
